//! Raw FFI bindings to `libllama`.
//!
//! Generated by `bindgen` from `vendor/llama.cpp/include/llama.h` at the
//! pinned commit (`vendor/llama.cpp.PIN.md`). Compiled in only when the
//! `llamacpp` cargo feature is enabled.
//!
//! The bindings are an internal implementation detail. The crate's public
//! API for inference is the `Backend` trait — adapters built on top of
//! these bindings live in sibling modules (e.g. `llamacpp.rs`, landing
//! in M2b).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(missing_docs)]
// Bindgen output triggers a number of style/clippy lints we accept for
// generated code only. Suppression is module-scoped; sibling modules in
// the crate stay subject to all lints.
#![allow(unsafe_code)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::all)]
#![allow(clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/llama_bindings.rs"));
