//! Raw FFI bindings to `libmtmd`.
//!
//! Generated by `bindgen` from `vendor/llama.cpp/tools/mtmd/mtmd.h` at
//! the pinned commit. Compiled in only when the `llamacpp` cargo
//! feature is enabled (per ADR 0016, multimodal is part of the
//! baseline llamacpp adapter shape).
//!
//! Shared types with `libllama` (`llama_model`, `llama_pos`, etc.)
//! are imported from the `crate::ffi` module rather than re-declared
//! — see the `raw_line` directive in `build.rs`. mtmd-specific types
//! (`mtmd_context`, `mtmd_bitmap`, ...) are defined here.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(unsafe_code)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::all)]
#![allow(clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/mtmd_bindings.rs"));
