//! `libllama` backend adapter (M2b).
//!
//! Implements the `Backend` trait against the FFI bindings generated by
//! `build.rs`. Compiled in only when the `llamacpp` cargo feature is on
//! (default builds use the `mock` adapter — see ADR 0005).
//!
//! The adapter splits two concerns:
//! - [`loader`] — open + verify + load the model file (THREAT_MODEL F-5,
//!   F-6).
//! - [`backend`] — the `Backend` impl: context, generation, cancellation.

pub mod backend;
pub mod loader;

pub use backend::{LlamaCpp, LlamaCppConfig, LlamaCppError};
pub use loader::{ModelHandle, ModelLoadError, load_model};
