//! `libllama` backend adapter (M2b).
//!
//! Implements the `Backend` trait against the FFI bindings generated by
//! `build.rs`. Compiled in only when the `llamacpp` cargo feature is on
//! (default builds use the `mock` adapter — see ADR 0005).
//!
//! The adapter splits two concerns:
//! - [`loader`] — open + verify + load the model file (THREAT_MODEL F-5,
//!   F-6).
//! - [`backend`] — the `Backend` impl: context, generation, cancellation.

#[cfg(feature = "dl-backends")]
pub mod accelerator;
pub mod backend;
pub mod chat_template;
pub mod grammar;
pub mod loader;
pub mod mtmd;
pub mod tool_parser;

#[cfg(feature = "dl-backends")]
pub use accelerator::{DeviceMemory, probe_accelerator, query_device_memory_for_kind};
pub use backend::{LlamaCpp, LlamaCppConfig, LlamaCppError};
pub use chat_template::{
    ChatFamily, ChatRenderer, Gemma4Renderer, GraniteRenderer, RenderError, Rendered, detect_family,
};
pub use loader::{ModelHandle, ModelLoadError, load_model};
pub use mtmd::{
    Bitmap, InputChunk, InputChunkKind, InputChunks, MmprojCaps, Mtmd, MtmdConfig, MtmdError,
    default_media_marker, probe_mmproj_caps,
};
